# Generated by Django 3.0.3 on 2020-08-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
